Mf/docs
eidolon-ai/eidolon pull request #678
Opened 2024-08-29 20:24 UTC by flynntsang

2024-08-29 20:32 UTC, LukeLalor requested changes
We should not need to install the clients to use the different llm providers, so I do not think this is required documentation

2024-09-03 15:17 UTC, flynntsang commented
@dbrewster could you take a look please? This is a proposal to add a new How to, specifically how to authenticate with your LLM providers.

2024-09-03 18:44 UTC, dbrewster submitted a review, later dismissed

2024-09-03 18:44 UTC, dbrewster commented on webui/apps/docs/astro.config.mjs
> +            {label: 'Build Custom Agent Templates', link: '/docs/howto/custom_agents'},
I like the new name.  Should we consider foo - bar - bar instead

2024-09-03 21:00 UTC, LukeLalor approved these changes
ship it

2024-09-04 01:08 UTC, merged